# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'POP Flix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for POP Flix
  pod 'UIImageColors', '~>2.1.0'

  target 'POP FlixTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
