platform :ios, '11.0'

target 'POP Flix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for POP Flix
  pod 'UIImageColors', '~>2.1.0'
  pod 'Alamofire', '~> 4.8.1'
  pod 'ARSLineProgress', '~> 3.1'
  pod 'RealmSwift', '~> 3.13.1'
 

  target 'POP FlixTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Fakery', '~> 3.4.0'
  end

end
